### PR TITLE
Add item level reference.

### PR DESCRIPTION
**Pull request by jrasanen**
Item level reference is used to provide more information to extranet and for shop-in-shop refunds. The uniqueness of this reference is not forced due to backward compatibility.

Merchants can issue refunds through our API and we try to focus the payment using merchant id, reference and stamp.

### CODE REVIEW

**Comment by mikaturunen** [comment]
Looks good. I see no problems. Anyone else?

**Comment by NikoLehtinen** [comment]
Is the status -10 (Palautettu) still there in Payment statuses? It should be removed.
Niko Lehtinen
Tekninen asiakasneuvoja
Checkout Finland Oy

**Comment by Ahtoranta** [comment]
Looks ok, no problemos.

**Comment by tekninentiimi** [comment]
Merge + publish new index.htm into the root so we can have this published. Thanks.

**Comment by mikaturunen** [comment]
As tekninentiimi put it earlier. Merge + release 👍

**Pull request merged**
